name: Cypress Tests

on:
  push:
    branches:
      - main  # Run tests on push to the main branch
  pull_request:
    branches:
      - main  # Run tests on pull requests to the main branch

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Match the Node.js version used locally

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          config-file: cypress.config.js  # Specify your Cypress config if necessary
